### ISSUE TITLE
More advanced functions

### ISSUE THREAD

**Issue by XenoHoe** [altaiiiir/Viner#1]
Thanks for the mod! It really filled high version forge's lack of a veinminer utility mod and I absolutely loved it. However, there's a few ideas that I would like to share.

The first is that the veinminer function works for any tool. This means that you can mine a diamond ore with a stone pick, and it would still drop. You can also mine ores with an axe, and all of them would still drop. SIlk touch enchantments on the tools are also not functional. This is clearly very broken in some cases.

My recommendation is that instead of just directly dropping the block, maybe consider the block to be broken by the tool in the player's hand. The vinable blocks should also be configured based on a "Tool Type A can break Block List A" system, with the list of tools in a tool type be customizable and the list of blocks breakable by that type of tool both be customizable, like the vein miner mod for older versions.

I also recommend adding a configurable limit to the amount of blocks that can be vined at a time. When I experimented with a large amount of same connected blocks, all of it got mined instantly and my game frozen instantly. This can cause some potential issues. A configurable limit to the amount of blocks that can be vined at a time can prevent this and really adds to the configurability of the mod.

Finally, I would be so happy if this mod can have an in game config screen. This can be done through config screen api such as cloth config.

Anyway, thanks again for the mod! Would be really glad if the mod gets even better!

**Comment by altaiiiir** [comment]
Thanks for the feedback! I will definitely be learning a lot more in an effort to expand this mod and implement the bug fixes ASAP. 

Also, I really appreciate the tip about the cloth config API! Still new to this field.

**Comment by cking** [comment]
there is also the forge config api, and a tool like https://modrinth.com/mod/forge-config-screens adds a fantastic UI for it to the game. (Or use Configured if you are fine with a CurseForge only mod, though not 1.20.* yet)
