### ISSUE TITLE
Vining ice turns them into air

### ISSUE THREAD

**Issue by XenoHoe** [altaiiiir/Viner#19]
Ice is expected to turn into water source blocks when mined without silk touch. However, if you hold the vine key and mine ice without silk touch(if ice is configured to be vinable), the ice would just break and turn into air, leaving an ugly hole made of air rather than turning into water.

<img width="1800" alt="Screenshot 2024-03-12 at 5 36 16 PM" src="https://github.com/altaiiiir/Viner/assets/88544456/f9b33c80-0544-442d-9820-2ff1954ad204">

**Comment by altaiiiir** [comment]
Thanks for the report Xeno! Looks like I'll need to have the mining logic take into consideration blocks that don't just completely disappear after being mined such as ice blocks.
