### ISSUE TITLE
Let me use tags instead of writing all ores one by one

### ISSUE THREAD

**Issue by cking** [altaiiiir/Viner#2]
Forge let's you tag (and query)  blocks based on tags.

That way, you can add a tag to the ore list and add a bunch of ores immediatly (eg `forge/ores` adds all vanilla ores and most modded ores whre devs added the tag.)

Makes it slightly easier and faster to add blocks to the list.

As blocks and ores share a common format, you would need to prefix it with something, like `#` for example.

**Comment by cking** [comment]
As an additional feature to this, it would be great to add a denylist, so you could add a tag or a block to a deny list to overwrite the allow list. Aka `forge:ores` in allow list, but deny `forge:ores_in_ground/deepslate` (aka every deepslate ore)

**Comment by altaiiiir** [comment]
Thanks a lot for leaving feedback! I'll definitely be expanding my knowledge about this tag feature, seems very handy. And I think you make a great point about expanding the config functionality, keep an eye out in the future! 

Also, any resources or documentation you can provide for this tag feature or anything would be amazing, still new and unsure where to find good docs about this stuff.

**Comment by testersen** [comment]
https://docs.minecraftforge.net/en/1.20.x/resources/server/tags/
