### ISSUE TITLE
Multiplayer Incompatible

### ISSUE THREAD

**Issue by WimpieRatte** [altaiiiir/Viner#5]
When I play with a friend (invited via Essential mod), his viner doesn't work... however whenever I use viner, it also activates for him.

**Comment by altaiiiir** [comment]
Thanks for the bug report! I will definitely take a look at this.

**Comment by TheJaysH** [comment]
I have taken a look at this and will be able to add it should @altaiiiir  want my assistance 😊

**Comment by altaiiiir** [comment]
@TheJaysH would appreciate your assistance if you're offering to help :) I've been stuck trying to replicate this, so any help would be greatly appreciated
