### ISSUE TITLE
add support for block tags in vineable_blocks.json

### ISSUE THREAD

**Issue by TheJaysH** [altaiiiir/Viner#7]
Duplicate cause i was on my wrong account lol.

Currently the mod only supports adding individual blocks via their full resource name. It would be a great addition to be able to add block tags to save adding each block.

```json
{
  "vineable_limit":5,
  "vineable_blocks": [
    "#minecraft:ores",
    "#forge:ores",
    "..."
  ]
}
```
I can submit a PR if/when i get a chance

**Comment by altaiiiir** [comment]
Hey Jay, thanks for leaving this suggestion! I actually got this suggestion before but I'm new to modding and never knew about these tags, seems like it would save a lot of time. A PR would be awesome! otherwise, I'll be looking into how I can utilize these

**Comment by HypNotiQ4** [comment]
> Hey Jay, thanks for leaving this suggestion! I actually got this suggestion before (guessing from your other account?) but I'm new to modding and never knew about these tags, seems like it would save a lot of time. A PR would be awesome! otherwise, I'll be looking into how I can utilize these

+1
using it with mystical agriculture right now & would be nice to be able to add "forge:ores" to the vineable blocks json.

**Comment by altaiiiir** [comment]
I’ve started researching on how these tags work! I’ll try to get something out soon hopefully. Quick clarification, you should be able to currently add any ore you want to the list, are you saying that manually adding a modded ore to the list is NOT working for you? That might be another fix I have to work on as well.

Thanks for your submission and feedback!

**Comment by HypNotiQ4** [comment]
> I’ve started researching on how these tags work! I’ll try to get something out soon hopefully. Quick clarification, you should be able to currently add any ore you want to the list, are you saying that manually adding a modded ore to the list is NOT working for you? That might be another fix I have to work on as well.
> 
> Thanks for your submission and feedback!

I do crash on launch if i add individual ores, i could be doing something wrong tho, so ill double check today

**Comment by TheJaysH** [comment]
I have updated the code and its working. Though be warned i got carried away and did a bit of a refactor lol. The only part i havent got down is migrating the old config. but i think a simple warning to users will suffice. will get a draft PR sent over soon.

**Comment by TheJaysH** [comment]
> > I’ve started researching on how these tags work! I’ll try to get something out soon hopefully. Quick clarification, you should be able to currently add any ore you want to the list, are you saying that manually adding a modded ore to the list is NOT working for you? That might be another fix I have to work on as well.
> > Thanks for your submission and feedback!
> 
> I do get an error when i launch if i add "mysticalagriculture:inferium_ore" or any of the other mystical agriculture ores, I could just be dumb & doing it wrong tho lol
> 
> I also noticed that the same ores of normal & deepslate don't mine together if theyre next to eachother, im not sure if there's a way for that to work or not but would be cool if it could

This is technically possible, however too much code needed to check each case.

**Comment by TheJaysH** [comment]
I've also fixed a bug where it didnt seem to do diagonals.

**Comment by TheJaysH** [comment]
I have submitted a Draft PR please can you link it to this issue.
